name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # or your production branch
  workflow_dispatch:  # Allow manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci
      working-directory: ./node-backend

    - name: Run tests
      run: npm test
      working-directory: ./node-backend
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2  # Change to your AWS region

    - name: Install Elastic Beanstalk CLI
      run: |
        pip install awsebcli
        
    - name: Deploy to Elastic Beanstalk
      working-directory: ./node-backend
      run: |
        eb deploy FreshFarmily-env
      env:
        # Pass GitHub secrets to the deployment environment
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    - name: Notify deployment status
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "✅ Deployment successful! Your application is now live."
          echo "Environment URL: http://freshfarmily-env.eba-xxxx.us-west-2.elasticbeanstalk.com"
        else
          echo "❌ Deployment failed. Check logs for details."
        fi
